import"./assets/footer-DQzmd3O7.js";import"./assets/vendor-nSNXNpMc.js";document.addEventListener("DOMContentLoaded",()=>{document.querySelector("#catalog");const d=document.querySelector("#genre-select"),a=document.querySelector("#load-more");let l=0;const c=6;let s=[],n=[];const h=["action","drama","comedy","horror","thriller"],v=()=>{const e=document.createElement("option");e.value="all",e.textContent="Genre",d.appendChild(e),h.forEach(t=>{const o=document.createElement("option");o.value=t,o.textContent=t.charAt(0).toUpperCase()+t.slice(1),d.appendChild(o)})},y=e=>{const t=document.createElement("span");return t.classList.add(`${e}-star`),t.innerHTML=e==="empty"?"&#9734;":"&#9733;",t},M=e=>{const t=document.createElement("div");t.classList.add("star-rating");const o=e/2,r=Math.floor(o),i=o%1>=.5?1:0,g=5-r-i;for(let p=0;p<r;p++)t.appendChild(y("full"));i&&t.appendChild(y("half"));for(let p=0;p<g;p++)t.appendChild(y("empty"));return t.outerHTML},u=(e,t)=>{const o=document.createDocumentFragment();e.forEach(r=>{const i=document.createElement("div");i.classList.add("film-card"),console.log(r);const g=r.vote_average;i.innerHTML=`
                <img src="https://image.tmdb.org/t/p/w500${r.poster||""}" alt="${r.title||""} poster" class="film-poster"/>
                <div class ="film-card-descr">
                <h3 class ="film-card-title">${r.title||""}</h3>
                <p class ="film-card-genre">${r.genres.slice(0,2).join(", ")||"N/A"}</p>
                <p class ="film-card-year"> ${r.year||""}</p>
                <p class ="film-card-stars">${M(g)||""}</p>
                </div>
            `,o.appendChild(i)}),t.append(o)},L=()=>{const e=JSON.parse(localStorage.getItem("myLibrary"))||[];return Array.isArray(e)?e:[]},m=document.querySelector(".catalog-films"),E=()=>{if(s=L(),m.innerHTML="",n=s,!Array.isArray(s)||s.length===0){console.warn("No movies found in library or library is not an array."),document.querySelector("#empty-library").style.display="block",a.style.display="none";return}u(n.slice(0,c),m),l=Math.min(c,n.length),a.style.display=l>=n.length?"none":"block"};a.addEventListener("click",()=>{const e=n.slice(l,l+c);u(e,m),l+=e.length,a.style.display=l>=n.length?"none":"block"}),d.addEventListener("change",e=>{const t=e.target.value;n=s.filter(o=>t==="all"||o.genres.map(r=>r.toLowerCase()).includes(t)),m.innerHTML="",u(n.slice(0,c),m),l=Math.min(c,n.length),a.style.display=l>=n.length?"none":"block"}),v(),E()});const f=document.querySelector("#genre-select");f.addEventListener("change",d=>{const a=d.target.value,l=document.querySelectorAll("#genre-select option");l.forEach(n=>n.style.color="#fff");const c=l[f.selectedIndex];c.style.color="orange";let s;a==="all"?s=allMovies:s=allMovies.filter(n=>n.genre_ids.includes(Number(a))),catFilms.innerHTML="",renderElements(s.slice(0,moviesPerPage),catFilms),displayedMovies=moviesPerPage});
//# sourceMappingURL=library.js.map
