import"./assets/footer-CqRdLSEq.js";import"./assets/vendor-nSNXNpMc.js";document.addEventListener("DOMContentLoaded",()=>{document.querySelector("#catalog");const p=document.querySelector("#genre-select"),i=document.querySelector("#load-more"),c=document.querySelector(".catalog-films");let l=0;const d=6;let m=[],n=[];const v=["action","adventure","animation","comedy","crime","documentary","drama","family","fantasy","horror","kids","mystery","news","politics","reality","sci-fi","soap","talk","thriller","war","western"],L=()=>{const e=document.createElement("option");e.value="all",e.textContent="Genre",p.appendChild(e),v.forEach(t=>{const a=document.createElement("option");a.value=t,a.textContent=t.charAt(0).toUpperCase()+t.slice(1),p.appendChild(a)})},y=e=>{const t=document.createElement("span");return t.classList.add(`${e}-star`),t.innerHTML=e==="empty"?"&#9734;":"&#9733;",t},b=e=>{const t=document.createElement("div");t.classList.add("star-rating");const a=e/2,r=Math.floor(a),o=a%1>=.5?1:0,g=5-r-o;for(let s=0;s<r;s++)t.appendChild(y("full"));o&&t.appendChild(y("half"));for(let s=0;s<g;s++)t.appendChild(y("empty"));return t.outerHTML},u=(e,t)=>{const a=document.createDocumentFragment();e.forEach(r=>{var h;const o=document.createElement("div");o.classList.add("film-card");const g=r.vote_average,s=r.poster?`https://image.tmdb.org/t/p/w500${r.poster}`:"default-image-url.jpg";o.innerHTML=`
                <button class="remove-movie" aria-label="Remove movie" data-title="${r.title}">&times;</button>
                <img src="${s}" alt="${r.title||""} poster" class="film-poster"/>
                <div class ="film-card-descr">
                  <h3 class ="film-card-title">${r.title||""}</h3>
                  <p class ="film-card-genre">${((h=r.genres)==null?void 0:h.slice(0,2).join(", "))||"N/A"}</p>
                  <p class ="film-card-year">${r.year||""}</p>
                  <p class ="film-card-stars">${b(g)||""}</p>
                </div>
            `,o.querySelector(".remove-movie").addEventListener("click",()=>{const S=r.title,E=(JSON.parse(localStorage.getItem("myLibrary"))||[]).filter(C=>C.title!==S);localStorage.setItem("myLibrary",JSON.stringify(E)),f()}),a.appendChild(o)}),t.append(a)},M=()=>{const e=JSON.parse(localStorage.getItem("myLibrary"))||[];return Array.isArray(e)?e:[]},f=()=>{if(m=M(),c.innerHTML="",n=m,!Array.isArray(m)||m.length===0){console.warn("No movies found in library or library is not an array."),document.querySelector("#empty-library").style.display="",i.style.display="none";return}u(n.slice(0,d),c),l=Math.min(d,n.length),i.style.display=l>=n.length?"none":"block"};i.addEventListener("click",()=>{const e=n.slice(l,l+d);u(e,c),l+=e.length,i.style.display=l>=n.length?"none":"block"}),p.addEventListener("change",e=>{const t=e.target.value;n=m.filter(a=>t==="all"||a.genres&&a.genres.map(r=>r.toLowerCase()).includes(t)),c.innerHTML="",u(n.slice(0,d),c),l=Math.min(d,n.length),i.style.display=l>=n.length?"none":"block"}),document.querySelector(".lib-empty-library-btn").addEventListener("click",()=>{window.location.href="catalog.html"}),L(),f()});
//# sourceMappingURL=library.js.map
